#!/bin/bash

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
hooks_dir="$repo_root/.git/hooks"

ln -sf "$repo_root/.scripts/pre-commit.detekt" "$hooks_dir/pre-commit"
chmod +x "$repo_root/.scripts/pre-commit.detekt"

echo "==== Finished installing the detekt pre-commit Git hook ===="